---
title: "HW4_SR"
author: "Sam Reeves"
date: "9/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preprocessing

We load the data and flatten the images into a vector representing pixels.

The flattened images can be manipulated with linear algebra.

```{r include = FALSE}
library(jpeg)
library(EBImage)

path = ("~/focm/wk4/")
setwd(path)
set.seed(1)

files <- list.files(path, pattern = '*.jpg')
n <- length(files)

h = 1200
w = 2500
c = 3

display_image <- function(im, add=FALSE) {
  # Initialize a plot, if there is none.
  res <- dim(im)[2:1]
  if (!add) {
    plot(1, 1,
         xlim = c(1, res[1]),
         ylim = c(1, res[2]),
         asp = 1,
         type = 'n',
         xaxs = 'i', yaxs = 'i',
         xaxt = 'n', yaxt = 'n',
         xlab = '', ylab = '',
         bty = 'n')
  rasterImage(im, 1, 1, res[1], res[2])
  }
}
```

Read test:

```{r}
display_image(readJPEG(files[1], native = TRUE))
```

We read the files in as a flattened array.

```{r}
build_array <- function(f = files) {
  # Create an array with all the image data flattened
  m <- matrix(0, (h*w*c), length(f))
  
  for (i in 1:length(f)) {
    image <- readJPEG(paste0(path, f[i]), native = TRUE)
    print(length(image))
    print(mean(image))
    #m[,i] = c(as.vector(image[,,1]), as.vector(image[,,2]), as.vector(image[,,3]))

  }
  return(m)
}

m <- build_array(files)
dim(m)
```

```{r}
plot_array <- function(files = files) {
  par(mfrow = c(3,3)) # Set graphics to 3x3
  par(mai = c(.2,.2,.2,.2)) # Set margins
  
  for (i in 1:n) {
    display_image(image_array[i])
  }
}

plot_array()
```


```{r}
display_image(image_array[1,,,])
```

## Eigenshoes

Remember that the eigenvalues are the same as the square of the standard deviation!

```{r}
image_correlation <- cor(t(as.matrix(image_array)))
(pca <- princomp(image_correlation, cor = TRUE, scores = TRUE))
```


```{r}
myEigen <- eigen(imCor)
myEigen
```

```{r}
pca$sdev
pca$loadings
```

```{r}
eigenShoes <- t(imMatrix) %*% myEigen$vectors %*% myEigen$values
```


```{r}
h <- 1200
w <- 2500
colors <- 3
const <- h*w*colors

x <- rep(rep(1:2500, 1200), 3)
y <-  rep(rep(1:1200, each = 2500), 3)
c <- rep(1:3, each = 3000000)
```

