---
title: "MIT Infinite Series notes"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Infinite Series

Improper Integrals (with a finite singularity)

Defin:
\[\int_0^1 f(x)dx = \lim_{a \to 0^+} \int_a^1 f(x)dx\]

The series converges if the limit exists, and diverges if not.

### Ex1.

\[\int_0^1 \frac{dx}{\sqrt{x}} = \int_0^1 x^{-\frac{1}{2}} dx\]

\[\left. 2x^{\frac{1}{2}} \right|_0^1 = 2 - 0\]

This one is convergent.

### Ex2.

\[\int_0^1 \frac{dx}{x} = \left. ln x \right|_0^1\]
\[= ln 1 - ln 0^+ = 0 - (-\inf) = \inf\]

This one diverges.

 ---
 
In general,

\[\int_0^1 \frac{dx}{x^p} = \left. \frac{1}{1-p} \right| p \ge 1\]

Contrast:

\[\frac{1}{x^{\frac{1}{2}}} < \frac{1}{x} < \frac{1}{x^2}\]

as $x \to 0^+$, and 

\[ \frac{1}{x^{\frac{1}{2}}} > \frac{1}{x} > \frac{1}{x^2}\] as $x \to \inf$

some are divergent........

 ---
 
### Series

\[1 + \frac{1}{2} + \frac{1}{4} + \frac{1}{8} + ... = 2\]

Geometric Series

\[1 + a + a^2 + a^3 + ... = \frac{1}{1-a}\]
\[|a| < 1, -1 < a < 1\]

Divergences:

\[a = 1, 1+1+1 + ... = \frac{1}{1-1} = \frac{1}{0}\]
NO no  no no no no no no no!

\[a = -1, 1-1+1-1 + ... = \frac{1}{1-(-1)} = \frac{1}{2}\]

\[a = 2, 1 + 2 + 2^2 + 2^3 + ... = \frac{1}{1-2} = -1\]

 ---
 
### Notation.
 
\[S_N = \sum_{n=0}^N a_n\]


\[S = \sum_{n=0}^{\infty} a_n = \lim_{N \to \infty} S_N\]

Either the limit exists, the series converges, or it does not exist, and the series does not converge.

### Ex3.

\[\sum_{n =1}^{\infty} \frac{1}{n^2} \sim \int_{1}^{\infty} \frac{dx}{x^2}\]

Euler computes that the first term here is equal to $\frac{\pi^2}{6}$, the second is equal to 1.

### Ex4.

\[\sum_{n=1}^{\infty} \frac{1}{n^3} \sim \int_{1}{\infty} \frac{dx}{x^3}\]

Here, the second term is equal to $\frac{1}{2}$ and the first is some impossible irrational number.

### Ex5.

\[\sum_{n=1}^{\infty} \frac{1}{n} \sim \int_{1}^{\infty} \frac{dx}{x}\]

This diverges!

Upper Riemann Sum --

\[\int_{1}^{N} \frac{dx}{x} < 1 + \frac{1}{2} + \frac{1}{3} + ... + \frac{1}{N-1} < S_N\]
\[S_N = 1 + \frac{1}{2} + ... + \frac{1}{N-1} + \frac{1}{N}\]

We can prove that these are divergent:

\[\int_{1}{N} \frac{dx}{x} < S_N\]
\[\int_{1}{N} \frac{dx}{x} = \left. lnx \right|_{1}^{N} = (ln N) - 0\]

\[ln N < S_N\]
\[(N \to \infty, S_N \to \infty)\]

We have shown divergence.

Lower Riemann Sum

\[\int_{1}^{N} \frac{dx}{x} > \frac{1}{2} + \frac{1}{3} + ... + \frac{1}{N} = S_N - 1\]
\[ln N < S_N < (lnN) + 1\]

 ---
 
### Integral Comparison

If $f(x)$ is decreasing and $f(x) > 0$, then:

\[\left|\sum_{n=1}^{\infty} f(n) - \int_{1}^{\infty} f(x)dx \right| < f(1)\]

and the sum and the integral converge or diverge together.


### Limit Comparison

If $f(n) \sim g(n)$, or $\frac{f(n)}{g(n)} \to \infty$ and $g(n) > 0$ (for all positive numbers), then $\sum f(n), \sum g(n)$ both either converge or diverge.

### Ex.

\[\sum \frac{1}{\sqrt{n^2 + 1}} \sim \sum \frac{1}{\sqrt{n^2}} = \sum \frac{1}{n}\]

These diverge together...

### Ex.

\[\sum_{2}^{\infty} \frac{1}{\sqrt{n^5 - n^2}} \sim \sum \frac{1}{\sqrt{n^5}} = \sum \frac{1}{n^{\frac{5}{2}}}\]

This converges.
